version: "3"
services:
  app:
    container_name: app_bolt
    build: ./.docker/bolt
    working_dir: /app
    volumes:
      - ./content:/app_bolt
    tty: true
    environment:
      SLACK_BOT_TOKEN: ""
      SLACK_APP_TOKEN: ""
      SLACK_SIGNING_SECRET: ""
      ZABBIX_TOKEN: ""
